import type React from "react"
import { useState } from "react"
import PageHero from "@/pages/PageHero"

export default function GetInvolvedPage(): React.JSX.Element {
  const [submitted, setSubmitted] = useState(false)
  const submit = (event: React.FormEvent<HTMLFormElement>): void => { event.preventDefault(); setSubmitted(true) }
  return <><PageHero eyebrow="Get involved" title="Bring your skills, questions, and commitments." intro="Volunteer with FDE, join the APrIGF Kathmandu conversation, or explore a partnership for more equitable digital futures." /><section className="section-space bg-white"><div className="container-wide grid gap-14 lg:grid-cols-[0.8fr_1.2fr]"><div><h2 className="text-3xl font-extrabold leading-tight">Work with us</h2><div className="mt-8 space-y-7 text-fde-charcoal/65"><p><strong className="text-fde-charcoal">Volunteer:</strong> Support community programmes, research, facilitation, or communications.</p><p><strong className="text-fde-charcoal">APrIGF Kathmandu:</strong> Join the regional dialogue on a safe, open, and inclusive internet.</p><p><strong className="text-fde-charcoal">Partner:</strong> Build public-interest technology and research with us.</p><a href="mailto:hello@fde.org.np" className="inline-block font-bold text-fde-orange">hello@fde.org.np</a></div></div><form onSubmit={submit} className="grid gap-5 border-t-2 border-fde-orange pt-7"><label className="text-sm font-bold">Name<input required name="name" className="mt-2 w-full border border-black/15 p-3 font-normal outline-none focus:border-fde-orange" /></label><label className="text-sm font-bold">Email<input required type="email" name="email" className="mt-2 w-full border border-black/15 p-3 font-normal outline-none focus:border-fde-orange" /></label><label className="text-sm font-bold">How would you like to contribute?<select name="interest" className="mt-2 w-full border border-black/15 bg-white p-3 font-normal"><option>Volunteer</option><option>APrIGF Kathmandu</option><option>Partnership</option></select></label><label className="text-sm font-bold">Message<textarea required name="message" rows={4} className="mt-2 w-full border border-black/15 p-3 font-normal outline-none focus:border-fde-orange" /></label><button type="submit" className="w-fit bg-fde-orange px-6 py-3 text-xs font-bold uppercase tracking-widest text-white hover:bg-fde-orange-dark">Send enquiry</button>{submitted && <p className="text-sm font-semibold text-fde-orange">Thank you. Your interest has been recorded.</p>}</form></div></section></>
}
